// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiAssetsBooksByIdData, DeleteApiAssetsBooksByIdResponses, DeleteApiAssetsLaptopsByIdData, DeleteApiAssetsLaptopsByIdResponses, DeleteApiMembersByIdData, DeleteApiMembersByIdResponses, GetApiAssetsBooksData, GetApiAssetsBooksResponses, GetApiAssetsData, GetApiAssetsLaptopsData, GetApiAssetsLaptopsResponses, GetApiAssetsResponses, GetApiMembersByIdData, GetApiMembersByIdResponses, GetApiMembersData, GetApiMembersResponses, PostApiAssetsBooksCheckoutByIdByMemberIdData, PostApiAssetsBooksCheckoutByIdByMemberIdResponses, PostApiAssetsBooksData, PostApiAssetsBooksResponses, PostApiAssetsBooksReturnByIdData, PostApiAssetsBooksReturnByIdResponses, PostApiAssetsLaptopsCheckoutByIdByMemberIdData, PostApiAssetsLaptopsCheckoutByIdByMemberIdResponses, PostApiAssetsLaptopsData, PostApiAssetsLaptopsResponses, PostApiAssetsLaptopsReturnByIdData, PostApiAssetsLaptopsReturnByIdResponses, PostApiMembersData, PostApiMembersResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiAssets = <ThrowOnError extends boolean = false>(options?: Options<GetApiAssetsData, ThrowOnError>) => (options?.client ?? client).get<GetApiAssetsResponses, unknown, ThrowOnError>({ url: '/api/Assets', ...options });

export const getApiAssetsBooks = <ThrowOnError extends boolean = false>(options?: Options<GetApiAssetsBooksData, ThrowOnError>) => (options?.client ?? client).get<GetApiAssetsBooksResponses, unknown, ThrowOnError>({ url: '/api/Assets/books', ...options });

export const postApiAssetsBooks = <ThrowOnError extends boolean = false>(options: Options<PostApiAssetsBooksData, ThrowOnError>) => (options.client ?? client).post<PostApiAssetsBooksResponses, unknown, ThrowOnError>({
    url: '/api/Assets/books',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiAssetsBooksCheckoutByIdByMemberId = <ThrowOnError extends boolean = false>(options: Options<PostApiAssetsBooksCheckoutByIdByMemberIdData, ThrowOnError>) => (options.client ?? client).post<PostApiAssetsBooksCheckoutByIdByMemberIdResponses, unknown, ThrowOnError>({ url: '/api/Assets/books/checkout/{id}/{memberId}', ...options });

export const postApiAssetsBooksReturnById = <ThrowOnError extends boolean = false>(options: Options<PostApiAssetsBooksReturnByIdData, ThrowOnError>) => (options.client ?? client).post<PostApiAssetsBooksReturnByIdResponses, unknown, ThrowOnError>({ url: '/api/Assets/books/return/{id}', ...options });

export const deleteApiAssetsBooksById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiAssetsBooksByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiAssetsBooksByIdResponses, unknown, ThrowOnError>({ url: '/api/Assets/books/{id}', ...options });

export const getApiAssetsLaptops = <ThrowOnError extends boolean = false>(options?: Options<GetApiAssetsLaptopsData, ThrowOnError>) => (options?.client ?? client).get<GetApiAssetsLaptopsResponses, unknown, ThrowOnError>({ url: '/api/Assets/laptops', ...options });

export const postApiAssetsLaptops = <ThrowOnError extends boolean = false>(options: Options<PostApiAssetsLaptopsData, ThrowOnError>) => (options.client ?? client).post<PostApiAssetsLaptopsResponses, unknown, ThrowOnError>({
    url: '/api/Assets/laptops',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiAssetsLaptopsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiAssetsLaptopsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiAssetsLaptopsByIdResponses, unknown, ThrowOnError>({ url: '/api/Assets/laptops/{id}', ...options });

export const postApiAssetsLaptopsCheckoutByIdByMemberId = <ThrowOnError extends boolean = false>(options: Options<PostApiAssetsLaptopsCheckoutByIdByMemberIdData, ThrowOnError>) => (options.client ?? client).post<PostApiAssetsLaptopsCheckoutByIdByMemberIdResponses, unknown, ThrowOnError>({ url: '/api/Assets/laptops/checkout/{id}/{memberId}', ...options });

export const postApiAssetsLaptopsReturnById = <ThrowOnError extends boolean = false>(options: Options<PostApiAssetsLaptopsReturnByIdData, ThrowOnError>) => (options.client ?? client).post<PostApiAssetsLaptopsReturnByIdResponses, unknown, ThrowOnError>({ url: '/api/Assets/laptops/return/{id}', ...options });

export const getApiMembers = <ThrowOnError extends boolean = false>(options?: Options<GetApiMembersData, ThrowOnError>) => (options?.client ?? client).get<GetApiMembersResponses, unknown, ThrowOnError>({ url: '/api/Members', ...options });

export const postApiMembers = <ThrowOnError extends boolean = false>(options: Options<PostApiMembersData, ThrowOnError>) => (options.client ?? client).post<PostApiMembersResponses, unknown, ThrowOnError>({
    url: '/api/Members',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiMembersById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiMembersByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiMembersByIdResponses, unknown, ThrowOnError>({ url: '/api/Members/{id}', ...options });

export const getApiMembersById = <ThrowOnError extends boolean = false>(options: Options<GetApiMembersByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiMembersByIdResponses, unknown, ThrowOnError>({ url: '/api/Members/{id}', ...options });
