// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5090/' | (string & {});
};

export type Asset = {
    id?: unknown;
    name?: string;
    itemCondition?: Condition;
    currentMemberId?: unknown;
};

export type Book = {
    author?: string;
    id?: unknown;
    name?: string;
    itemCondition?: Condition;
    currentMemberId?: unknown;
};

export type Condition = number;

export type Laptop = {
    serialNumber?: string;
    os?: string;
    id?: unknown;
    name?: string;
    itemCondition?: Condition;
    currentMemberId?: unknown;
};

export type Member = {
    id?: unknown;
    name?: string;
    email?: string;
};

export type GetApiAssetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Assets';
};

export type GetApiAssetsResponses = {
    /**
     * OK
     */
    200: Array<Asset>;
};

export type GetApiAssetsResponse = GetApiAssetsResponses[keyof GetApiAssetsResponses];

export type GetApiAssetsBooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Assets/books';
};

export type GetApiAssetsBooksResponses = {
    /**
     * OK
     */
    200: Array<Book>;
};

export type GetApiAssetsBooksResponse = GetApiAssetsBooksResponses[keyof GetApiAssetsBooksResponses];

export type PostApiAssetsBooksData = {
    body: Book;
    path?: never;
    query?: never;
    url: '/api/Assets/books';
};

export type PostApiAssetsBooksResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAssetsBooksCheckoutByIdByMemberIdData = {
    body?: never;
    path: {
        id: unknown;
        memberId: unknown;
    };
    query?: never;
    url: '/api/Assets/books/checkout/{id}/{memberId}';
};

export type PostApiAssetsBooksCheckoutByIdByMemberIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAssetsBooksReturnByIdData = {
    body?: never;
    path: {
        id: unknown;
    };
    query?: never;
    url: '/api/Assets/books/return/{id}';
};

export type PostApiAssetsBooksReturnByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiAssetsBooksByIdData = {
    body?: never;
    path: {
        id: unknown;
    };
    query?: never;
    url: '/api/Assets/books/{id}';
};

export type DeleteApiAssetsBooksByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAssetsLaptopsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Assets/laptops';
};

export type GetApiAssetsLaptopsResponses = {
    /**
     * OK
     */
    200: Array<Laptop>;
};

export type GetApiAssetsLaptopsResponse = GetApiAssetsLaptopsResponses[keyof GetApiAssetsLaptopsResponses];

export type PostApiAssetsLaptopsData = {
    body: Laptop;
    path?: never;
    query?: never;
    url: '/api/Assets/laptops';
};

export type PostApiAssetsLaptopsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiAssetsLaptopsByIdData = {
    body?: never;
    path: {
        id: unknown;
    };
    query?: never;
    url: '/api/Assets/laptops/{id}';
};

export type DeleteApiAssetsLaptopsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAssetsLaptopsCheckoutByIdByMemberIdData = {
    body?: never;
    path: {
        id: unknown;
        memberId: unknown;
    };
    query?: never;
    url: '/api/Assets/laptops/checkout/{id}/{memberId}';
};

export type PostApiAssetsLaptopsCheckoutByIdByMemberIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAssetsLaptopsReturnByIdData = {
    body?: never;
    path: {
        id: unknown;
    };
    query?: never;
    url: '/api/Assets/laptops/return/{id}';
};

export type PostApiAssetsLaptopsReturnByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Members';
};

export type GetApiMembersResponses = {
    /**
     * OK
     */
    200: Array<Member>;
};

export type GetApiMembersResponse = GetApiMembersResponses[keyof GetApiMembersResponses];

export type PostApiMembersData = {
    body: Member;
    path?: never;
    query?: never;
    url: '/api/Members';
};

export type PostApiMembersResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiMembersByIdData = {
    body?: never;
    path: {
        id: unknown;
    };
    query?: never;
    url: '/api/Members/{id}';
};

export type DeleteApiMembersByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiMembersByIdData = {
    body?: never;
    path: {
        id: unknown;
    };
    query?: never;
    url: '/api/Members/{id}';
};

export type GetApiMembersByIdResponses = {
    /**
     * OK
     */
    200: Member;
};

export type GetApiMembersByIdResponse = GetApiMembersByIdResponses[keyof GetApiMembersByIdResponses];
